// Mock ElasticSearch response data for testing
export default {
  hits: {
    total: {
      value: 5,
      relation: 'eq',
    },
    max_score: 1.0,
    hits: [
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '123',
        _score: 1.0,
        _source: {
          id: 123,
          prefix: 'Dr.',
          first_name: 'Jane',
          last_name: 'Doe',
          suffix: 'MD',
          title: 'Cardiologist',
          accepts_new_patients: 1,
          avg_rating: 4.8,
          bio: 'Dr. Doe is a board-certified cardiologist specializing in preventive cardiology.',
          brief_bio: 'Expert cardiologist focused on prevention',
          specialty: [
            {
              id: 2,
              specialty_id: 201,
              specialty_name: 'Cardiology',
              sub_specialty_name: 'Preventive Cardiology',
              primary_specialty: 1,
              provider_id: 123,
              specialty_friendly_url: 'cardiology',
            },
          ],
          practice: [
            {
              id: 2,
              name: 'Heart Care Specialists',
              address: '456 Cardiology Center',
              city_name: 'New York',
              state_name: 'NY',
              zipcode: '10001',
              phone_number: '212-555-0456',
              email: 'jane.doe@heartcare.com',
              website: 'www.heartcare.com',
              latitude: 40.7505,
              longitude: -73.9934,
              out_of_network: false,
            },
          ],
        },
      },
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '1',
        _score: 1.0,
        _source: {
          id: 1,
          prefix: 'Dr.',
          first_name: 'John',
          last_name: 'Smith',
          suffix: 'MD',
          title: 'Family Medicine',
          accepts_new_patients: 1,
          avg_rating: 4.5,
          bio: 'Dr. Smith is a board-certified family medicine physician with over 15 years of experience.',
          brief_bio: 'Experienced family medicine physician',
          specialty: [
            {
              id: 1,
              specialty_id: 101,
              specialty_name: 'Family Medicine',
              sub_specialty_id: null,
              sub_specialty_name: null,
              primary_specialty: 1,
              provider_id: 1,
              rel_id: 1,
              specialty_friendly_url: 'family-medicine',
              specialty_name_schemaorg: 'Family Medicine',
              taxonomy_code: '207Q00000X',
            },
          ],
          practice: [
            {
              id: 1,
              name: 'Family Care Center',
              address: '123 Medical Plaza',
              city_name: 'New York',
              state_name: 'NY',
              zipcode: '10001',
              phone_number: '212-555-0123',
              email: 'john.smith@familycare.com',
              website: 'www.familycare.com',
              latitude: 40.7128,
              longitude: -74.006,
              out_of_network: 0,
              practice_id: 1,
              provider_id: 1,
              rel_id: 1,
              city_id: 1,
              state_id: 1,
              location: {
                lat: 40.7128,
                lon: -74.006,
              },
              coverage_location: {
                lat: 40.7128,
                lon: -74.006,
              },
              city_friendly_url: 'new-york',
              state_friendly_url: 'ny',
              state_abbreviation: 'NY',
              verified: 1,
            },
          ],
          award: [
            {
              id: 1,
              award_name: 'Top Doctor',
              awarding_institution: 'New York Magazine',
              received_years: '2023',
              provider_id: 1,
              rel_id: 1,
            },
          ],
          certification: [
            {
              id: 1,
              certification_specialty_name: 'Family Medicine',
              certification_sub_specialty_name: null,
              certifying_body_name: 'American Board of Family Medicine',
              year_achieved: 2010,
              provider_id: 1,
              rel_id: 1,
              certification_specialty_id: 101,
              certification_sub_specialty_id: null,
              certification_type_id: 1,
              certification_type_name: 'Board Certification',
              certifying_body_id: 1,
            },
          ],
          education: [
            {
              id: 1,
              education_type_name: 'Medical School',
              education_name: 'Harvard Medical School',
              graduation_year: 2000,
              area_of_focus: 'Medicine',
              provider_id: 1,
              rel_id: 1,
              education_name_id: 1,
              education_type_id: 1,
              started_year: 1996,
            },
          ],
          virtual_visit: [
            {
              id: 1,
              enabled: 1,
              accept_new_patients: 1,
              name: 'Teladoc',
              provider_id: 1,
              rel_id: 1,
              account_id: 1,
            },
          ],
          provider_id: 1,
          npi_id: '1234567890',
          year_began_practicing: 2001,
          gender: 'M',
          claimed: 1,
          verified: 1,
          schedule_online: 1,
          docscore: 95,
        },
      },
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '2',
        _score: 1.0,
        _source: {
          id: 2,
          prefix: 'Dr.',
          first_name: 'Igor',
          last_name: 'Korotkov',
          suffix: 'MD',
          title: 'Cardiologist',
          accepts_new_patients: 1,
          avg_rating: 4.8,
          bio: 'Dr. Igor Korotkov is a board-certified cardiologist specializing in interventional cardiology.',
          brief_bio: 'Expert cardiologist with interventional specialty',
          specialty: [
            {
              id: 2,
              specialty_id: 102,
              specialty_name: 'Cardiology',
              sub_specialty_id: 201,
              sub_specialty_name: 'Interventional Cardiology',
              primary_specialty: 1,
              provider_id: 2,
              rel_id: 2,
              specialty_friendly_url: 'cardiology',
              specialty_name_schemaorg: 'Cardiology',
              taxonomy_code: '207RC0000X',
            },
          ],
          practice: [
            {
              id: 2,
              name: 'Heart Care Center',
              address: '456 Medical Plaza',
              city_name: 'New York',
              state_name: 'NY',
              zipcode: '10001',
              phone_number: '212-555-0456',
              email: 'igor.korotkov@heartcare.com',
              website: 'www.heartcare.com',
              latitude: 40.7128,
              longitude: -74.006,
              out_of_network: 0,
              practice_id: 2,
              provider_id: 2,
              rel_id: 2,
              city_id: 1,
              state_id: 1,
              location: {
                lat: 40.7128,
                lon: -74.006,
              },
              coverage_location: {
                lat: 40.7128,
                lon: -74.006,
              },
              city_friendly_url: 'new-york',
              state_friendly_url: 'ny',
              state_abbreviation: 'NY',
              verified: 1,
            },
          ],
          award: [
            {
              id: 2,
              award_name: 'Top Cardiologist',
              awarding_institution: 'American Heart Association',
              received_years: '2023',
              provider_id: 2,
              rel_id: 2,
            },
          ],
          certification: [
            {
              id: 2,
              certification_specialty_name: 'Cardiovascular Disease',
              certification_sub_specialty_name: 'Interventional Cardiology',
              certifying_body_name: 'American Board of Internal Medicine',
              year_achieved: 2012,
              provider_id: 2,
              rel_id: 2,
              certification_specialty_id: 102,
              certification_sub_specialty_id: 201,
              certification_type_id: 1,
              certification_type_name: 'Board Certification',
              certifying_body_id: 2,
            },
          ],
          education: [
            {
              id: 2,
              education_type_name: 'Medical School',
              education_name: 'Yale School of Medicine',
              graduation_year: 2005,
              area_of_focus: 'Cardiology',
              provider_id: 2,
              rel_id: 2,
              education_name_id: 2,
              education_type_id: 1,
              started_year: 2001,
            },
          ],
          virtual_visit: [
            {
              id: 2,
              enabled: 1,
              accept_new_patients: 1,
              name: 'Teladoc',
              provider_id: 2,
              rel_id: 2,
              account_id: 2,
            },
          ],
          provider_id: 2,
          npi_id: '0987654321',
          year_began_practicing: 2006,
          gender: 'M',
          claimed: 1,
          verified: 1,
          schedule_online: 1,
          docscore: 98,
        },
      },
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '3',
        _score: 1.0,
        _source: {
          id: 3,
          prefix: 'Dr.',
          first_name: 'Sarah',
          last_name: 'Chen',
          suffix: 'MD',
          title: 'Neurologist',
          accepts_new_patients: 1,
          avg_rating: 4.9,
          bio: 'Dr. Sarah Chen is a board-certified neurologist specializing in movement disorders and neurodegenerative diseases.',
          brief_bio: 'Expert neurologist focused on movement disorders',
          specialty: [
            {
              id: 2,
              specialty_id: 103,
              specialty_name: 'Neurology',
              sub_specialty_id: 301,
              sub_specialty_name: 'Movement Disorders',
              primary_specialty: 1,
              provider_id: 2,
              rel_id: 2,
              specialty_friendly_url: 'neurology',
              specialty_name_schemaorg: 'Neurology',
              taxonomy_code: '207RN0000X',
            },
          ],
          practice: [
            {
              id: 2,
              name: 'Brain & Spine Center',
              address: '456 Medical Center Drive',
              city_name: 'San Francisco',
              state_name: 'CA',
              zipcode: '94143',
              phone_number: '415-555-0789',
              email: 'sarah.chen@brainspine.com',
              website: 'www.brainspine.com',
              latitude: 37.7749,
              longitude: -122.4194,
              out_of_network: 0,
              practice_id: 2,
              provider_id: 2,
              rel_id: 2,
              city_id: 1,
              state_id: 1,
              location: {
                lat: 37.7749,
                lon: -122.4194,
              },
              coverage_location: {
                lat: 37.7749,
                lon: -122.4194,
              },
              city_friendly_url: 'san-francisco',
              state_friendly_url: 'ca',
              state_abbreviation: 'CA',
              verified: 1,
            },
          ],
          award: [
            {
              id: 2,
              award_name: 'Excellence in Neurology',
              awarding_institution: 'American Academy of Neurology',
              received_years: '2023',
              provider_id: 2,
              rel_id: 2,
            },
          ],
          certification: [
            {
              id: 2,
              certification_specialty_name: 'Neurology',
              certification_sub_specialty_name: 'Movement Disorders',
              certifying_body_name: 'American Board of Psychiatry and Neurology',
              year_achieved: 2014,
              provider_id: 2,
              rel_id: 2,
              certification_specialty_id: 103,
              certification_sub_specialty_id: 301,
              certification_type_id: 1,
              certification_type_name: 'Board Certification',
              certifying_body_id: 2,
            },
          ],
          education: [
            {
              id: 2,
              education_type_name: 'Medical School',
              education_name: 'Stanford School of Medicine',
              graduation_year: 2007,
              area_of_focus: 'Neurology',
              provider_id: 2,
              rel_id: 2,
              education_name_id: 2,
              education_type_id: 1,
              started_year: 2003,
            },
          ],
          virtual_visit: [
            {
              id: 2,
              enabled: 1,
              accept_new_patients: 1,
              name: 'Teladoc',
              provider_id: 2,
              rel_id: 2,
              account_id: 2,
            },
          ],
          provider_id: 2,
          npi_id: '0987654321',
          year_began_practicing: 2008,
          gender: 'F',
          claimed: 1,
          verified: 1,
          schedule_online: 1,
          docscore: 97,
        },
      },
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '4',
        _score: 1.0,
        _source: {
          id: 4,
          prefix: 'Dr.',
          first_name: 'Michael',
          last_name: 'Rodriguez',
          suffix: 'MD',
          title: 'Pediatrician',
          accepts_new_patients: 1,
          avg_rating: 4.7,
          bio: 'Dr. Rodriguez is a compassionate pediatrician with expertise in childhood development and preventive care.',
          brief_bio: 'Dedicated pediatrician focused on child wellness',
          specialty: [
            {
              id: 4,
              specialty_id: 104,
              specialty_name: 'Pediatrics',
              sub_specialty_name: 'General Pediatrics',
              primary_specialty: 1,
              provider_id: 4,
              specialty_friendly_url: 'pediatrics',
            },
          ],
          practice: [
            {
              id: 4,
              name: 'Kids First Pediatrics',
              address: "789 Children's Way",
              city_name: 'Los Angeles',
              state_name: 'CA',
              zipcode: '90045',
              phone_number: '310-555-0789',
              email: 'michael.rodriguez@kidsfirst.com',
              website: 'www.kidsfirst.com',
              latitude: 34.0522,
              longitude: -118.2437,
              out_of_network: false,
            },
          ],
          award: [
            {
              id: 4,
              award_name: 'Best Pediatrician',
              awarding_institution: 'LA Parents Magazine',
              received_years: '2022',
              provider_id: 4,
              rel_id: 4,
            },
          ],
          certification: [
            {
              id: 4,
              certification_specialty_name: 'Pediatrics',
              certification_sub_specialty_name: null,
              certifying_body_name: 'American Board of Pediatrics',
              year_achieved: 2015,
              provider_id: 4,
              rel_id: 4,
            },
          ],
          education: [
            {
              id: 4,
              education_type_name: 'Medical School',
              education_name: 'UCLA School of Medicine',
              graduation_year: 2010,
              area_of_focus: 'Pediatrics',
              provider_id: 4,
              rel_id: 4,
            },
          ],
          virtual_visit: [
            {
              id: 4,
              enabled: 1,
              accept_new_patients: 1,
              name: 'KidsConnect',
              provider_id: 4,
              rel_id: 4,
              account_id: 4,
            },
          ],
          provider_id: 4,
          npi_id: '5432109876',
          year_began_practicing: 2011,
          gender: 'M',
          claimed: 1,
          verified: 1,
          schedule_online: 1,
          docscore: 94,
        },
      },
      {
        _index: 'doctors',
        _type: '_doc',
        _id: '5',
        _score: 1.0,
        _source: {
          id: 5,
          prefix: 'Dr.',
          first_name: 'Emily',
          last_name: 'Parker',
          suffix: 'MD',
          title: 'Dermatologist',
          accepts_new_patients: 1,
          avg_rating: 4.6,
          bio: 'Dr. Parker is a skilled dermatologist specializing in both medical and cosmetic dermatology.',
          brief_bio: 'Expert dermatologist in medical and cosmetic care',
          specialty: [
            {
              id: 5,
              specialty_id: 105,
              specialty_name: 'Dermatology',
              sub_specialty_name: 'Medical Dermatology',
              primary_specialty: 1,
              provider_id: 5,
              specialty_friendly_url: 'dermatology',
            },
          ],
          practice: [
            {
              id: 5,
              name: 'Parker Dermatology',
              address: '321 Skin Care Blvd',
              city_name: 'Chicago',
              state_name: 'IL',
              zipcode: '60601',
              phone_number: '312-555-9876',
              email: 'emily.parker@parkerdermatology.com',
              website: 'www.parkerdermatology.com',
              latitude: 41.8781,
              longitude: -87.6298,
              out_of_network: false,
            },
          ],
          award: [
            {
              id: 5,
              award_name: 'Excellence in Dermatology',
              awarding_institution: 'American Academy of Dermatology',
              received_years: '2023',
              provider_id: 5,
              rel_id: 5,
            },
          ],
          certification: [
            {
              id: 5,
              certification_specialty_name: 'Dermatology',
              certification_sub_specialty_name: null,
              certifying_body_name: 'American Board of Dermatology',
              year_achieved: 2013,
              provider_id: 5,
              rel_id: 5,
            },
          ],
          education: [
            {
              id: 5,
              education_type_name: 'Medical School',
              education_name: 'Northwestern University Medical School',
              graduation_year: 2008,
              area_of_focus: 'Dermatology',
              provider_id: 5,
              rel_id: 5,
            },
          ],
          virtual_visit: [
            {
              id: 5,
              enabled: 1,
              accept_new_patients: 1,
              name: 'DermConnect',
              provider_id: 5,
              rel_id: 5,
              account_id: 5,
            },
          ],
          provider_id: 5,
          npi_id: '6789054321',
          year_began_practicing: 2009,
          gender: 'F',
          claimed: 1,
          verified: 1,
          schedule_online: 1,
          docscore: 93,
        },
      },
    ],
  },
};
