/* eslint-disable */

module.exports = [
    {old_var: '--color-button-outline-core-focused-border-core', new_var: '--color-button-branded-tertiary-default-focused-border-core'}, 
    {old_var: '--color-button-filled-core-reversed-surface-default', new_var: '--color-button-branded-primary-reversed-surface-default'}, 
    {old_var: '--color-button-filled-core-foreground-default', new_var: '--color-button-branded-primary-default-foreground-default'}, 
    {old_var: '--color-button-filled-core-reversed-foreground-default', new_var: '--color-button-branded-primary-reversed-foreground-default'}, 
    {old_var: '--color-button-filled-core-surface-hover', new_var: '--color-button-branded-primary-default-surface-hover'}, 
    {old_var: '--color-button-filled-core-reversed-surface-hover', new_var: '--color-button-branded-primary-reversed-surface-hover'}, 
    {old_var: '--color-button-filled-core-surface-disabled', new_var: '--color-button-branded-primary-default-surface-disabled'}, 
    {old_var: '--color-button-filled-core-reversed-surface-disabled', new_var: '--color-button-branded-primary-reversed-surface-disabled'}, 
    {old_var: '--color-button-filled-core-foreground-disabled', new_var: '--color-button-branded-primary-default-foreground-disabled'}, 
    {old_var: '--color-button-filled-core-reversed-foreground-disabled', new_var: '--color-button-branded-primary-reversed-foreground-disabled'}, 
    {old_var: '--color-button-outline-core-disbled', new_var: '--color-button-branded-tertiary-default-disbled'}, 
    {old_var: '--color-button-outline-core-disbled', new_var: '--color-button-branded-secondary-default-disbled'}, 
    //{old_var: 'rgba(0, 0, 0, 0)', new_var: '--color-button-branded-secondary-reversed-surface-hover'},
    // {old_var: '-', new_var: '--color-button-branded-secondary-default-surface-hover'}, 
    {old_var: '--color-button-outline-core-reversed-disabled', new_var: '--color-button-branded-tertiary-reversed-disabled'}, 
    {old_var: '--color-button-outline-core-default', new_var: '--color-button-branded-tertiary-default-default'}, 
    {old_var: '--color-button-outline-core-default', new_var: '--color-button-branded-secondary-default-foreground-default'}, 
    {old_var: '--color-button-outline-core-default', new_var: '--color-button-branded-secondary-default-border-default'}, 
    {old_var: '--color-button-outline-core-default', new_var: '--color-button-branded-tertiary-default-default'}, 
    {old_var: '--color-button-filled-core-surface-default', new_var: '--color-button-branded-primary-default-surface-default'}, 
    {old_var: '--color-button-filled-core-surface-default', new_var: '--color-button-branded-primary-default-surface-default'}, 
    {old_var: '--color-button-outline-core-hover', new_var: '--color-button-branded-tertiary-default-hover'}, 
    {old_var: '--color-button-outline-core-hover', new_var: '--color-button-branded-secondary-default-foreground-hover'}, 
    {old_var: '--color-button-outline-core-reversed-default', new_var: '--color-button-branded-tertiary-reversed-default'}, 
    {old_var: '--color-button-outline-core-reversed-default', new_var: '--color-button-branded-secondary-reversed-foreground-default'}, 
    {old_var: '--color-button-outline-core-reversed-default', new_var: '--color-button-branded-secondary-reversed-border-default'}, 
]
 